### ISSUE TITLE
How do you work this

### ISSUE THREAD

**Issue by WJ0F** [CheeseDanish1/Rosetta-Stone-Hack#3]
maybe include a video/ text tutorial on how exactly to get it working perhaps?

**Comment by heroakatry** [comment]
yeah and how do you execute it?

**Comment by helloeverything1** [comment]
It's explained pretty well in the usage section, I haven't used it but my assumption would be clone the git repo to a folder, install  [node.js](https://nodejs.org/en/download), set the constants.json to what you need (use network tab in inspect element to get those values, it says what request has them), and then open a command prompt in the folder with everything in it, and run node index.js as shown in the readme.

**Comment by Cubinster** [comment]
can someone make a video on how to do this

**Comment by heroakatry** [comment]
i still dont know how to do this can the owner please contact me on disscord? ; jeweetniets

**Comment by heroakatry** [comment]
I finally know how to execute the project. but it works alr but my progress is not going up meanwill all the task are made
or did i do something wrong?

**Comment by CheeseDanish1** [comment]
Do you properly set up the configeration.json file? Are you receiving 200 Status messages in the console? What do you mean by "all the task are made"? Are you using nodejs or the browser terminal? Please provide more information so I can help you. If you want to send me more information my discord is acanecti.

**Comment by Cubinster** [comment]
Can you please make a video on how to do it

**Comment by CheeseDanish1** [comment]
I would love to make a video on how to use this. Unfortunately, I no longer have access to my Rosetta Stone account. If someone who has successfully used it can make a video, that would be greatly appreciated. Until then, I can give individual help on GitHub or Discord.

**Comment by stalin182** [comment]
I can I can lend you my account so you can explain, please

**Comment by stalin182** [comment]
i need to know how to use it :c i just have 3 days to finish 17 units :c

**Comment by CheeseDanish1** [comment]
Ok. How do you want to communicate? Discord, Email or something else?

**Comment by stalin182** [comment]
Discord it´s fine  this is my user name: **stanb182**
I'm not so good with pc, or software, if you could help me will be amazing

**Comment by stalin182** [comment]
How can i find you at discord?

**Comment by CheeseDanish1** [comment]
My discord is above. I've also added you.

**Comment by CheeseDanish1** [comment]
I've posted some videos in the README.MD. If anyone has more questions, open a new thread. I think everything is covered so I'm marking this as closed.

**Comment by shep-ard** [comment]
I get that same issue
