### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by tuenny** [CheeseDanish1/Rosetta-Stone-Hack#4]
I did all the steps but the units are not completed, I don't know what am I doing wrong. Hope you can help me.

**Comment by CheeseDanish1** [comment]
I just used it yesterday and it worked great. Please send the console output when you try running the program so I can be of more assistance. If you want to contact me privately my discord is Acanecti.

**Comment by tuenny** [comment]
Problem solved! I definitely was doing something wrong in the process. Followed the instructions again and it worked.
